### ISSUE TITLE
Reduce loading times in docs

### ISSUE THREAD

**Issue by AntonioMateoGomez** [arrow-kt/arrow-site#27]
Right now we seem to load all runnable snippets at once, and takes a few seconds after loading a page. It's around 7-8 seconds for me, meanwhile nothing is clickable. Once snippets are loaded everything goes back to normal.

[This page can be a good example of the issue](https://arrow-kt.io/docs/fx/)

We may should do lazy loading on scroll and load them like one by one to fix that problem.

**Comment by AntonioMateoGomez** [comment]
Closed through #45

**Comment by rachelcarmena** [comment]
@AntonioMateoGomez , @AntonioMateoGomez , thanks for the improvement!! I was talking to @JorgeCastilloPrz about it, because he still notices a different load time with: https://arrow-kt.io/docs/0.10/fx/. He was comparing the time with https://arrow-kt.io/docs/0.10/fx/async/

And it's true, it's really different.

So... I compared the source code for both pages and... :tada: there are 2 Easter eggs at  https://arrow-kt.io/docs/0.10/fx/ :sweat_smile: 

Please, open the code snippets for `Side effects` section and the second one for `Applying side effects with !effect`. 

I'll create an issue to fix them :wink:

**Comment by rachelcarmena** [comment]
"fix them" = instead of running the compilation with an error, disable execution and show the error.

**Comment by calvellido** [comment]
I feel like those errors (the easter eggs :sweat_smile: ) are on the Ank side, as Arrow Playground doesn't interpret the code snippet unless is set as executable and you hit the button.

**Comment by rachelcarmena** [comment]
> I feel like those errors (the easter eggs sweat_smile ) are on the Ank side, as Arrow Playground doesn't interpret the code snippet unless is set as executable and you hit the button.

Right! Thanks @calvellido. However, they are more than 2 thousand lines of multiple span sections and then hidden. Let's see what happens if they are removed because it's the only difference in that page. Thanks!!! :raised_hands:

**Comment by calvellido** [comment]
Ahh yeah, I see what you mean now.  Right spotted!  Yeah, that could be degrading performance as the snippets got analyzed through `hljs` too, so a big chunk could be making that process to slow the load.

**Comment by rachelcarmena** [comment]
> Ahh yeah, I see what you mean now. Right spotted! Yeah, that could be degrading performance as the snippets got analyzed through `hljs` too, so a big chunk could be making that process to slow the load.

Thanks!! Let's see what happens when they are removed. However, this fix improved the load time as well. Thanks!!! :raised_hands:
